### ISSUE TITLE
Enter another dataverse URL

### ISSUE THREAD

**Issue by Bertverbeek4PS** [microsoft/bc2dataverse#2]
Once you have entered an dataverse URL in a project using the command "bc2dataverse: Generate proxy table" and you get the wrong one you cannot switch to another Dataverse URL.
There is no clear function. Even when you remove the extension.

**Comment by DuttaSoumya** [comment]
Hi Bert,

You are right. The Dataverse URL (among other settings) is actually stored in the workspace settings. If you remove those settings, the tool will prompt you again for another URL.

I am curious to know if it is common to connect to many different Dataverse environments from a single VS Code client.

Best regards,
Dutta.

**Comment by Bertverbeek4PS** [comment]
Hi Soumya, 
Well I think it is not common to change allot the url.
In my case I made a mistake in the url and when I try it again he didn't show me the url.

In development time mostly you get it from a test database. Later in the project that will move. But that is nog very often. Maybe once in a project.

But maybe for some typo a clear function would be nice.
Think it is more a nice to have feature and not a must.

Regards,
Bert

**Comment by DuttaSoumya** [comment]
Thanks Bert for that explanation. I hope for these situations, you could clear the settings from the workspace and re-try.

Best regards.

**Comment by Bertverbeek4PS** [comment]
Yes indeed. Maybe if it is not subscribe we must do that.
Thanks Soumya for your reply.
